/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ooieueioo_potestjni_PoJNITtest */

#ifndef _Included_com_ooieueioo_potestjni_PoJNITtest
#define _Included_com_ooieueioo_potestjni_PoJNITtest
#ifdef __cplusplus
extern "C" {
#endif

/***** Po area
 *
*/
JNIEXPORT jstring JNICALL Java_com_ooieueioo_potestjni_PoJNITtest_ReadMacAddress(JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
