/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ooieuioo_potestjni_PoJNITtest */

#ifndef _Included_com_ooieuioo_potestjni_PoJNITtest
#define _Included_com_ooieuioo_potestjni_PoJNITtest
#ifdef __cplusplus
extern "C" {
#endif

/**
 * Class: com_ooieuioo_potestjni_PoJNITtest
 * Method: HelloWorld
 * Signature: ()Ljava/lang/String
 */
JNIEXPORT jstring JNICALL Java_com_ooieuioo_potestjni_PoJNITtest_HelloWorld(JNIEnv *, jclass);

/**
 * Class: com_ooieuioo_potestjni_PoJNITtest
 * Method: TransportStringToC, Java send String to C, then C return string
 * Signature: ()Ljava/lang/String
 */
JNIEXPORT jstring JNICALL Java_com_ooieuioo_potestjni_PoJNITtest_TransportStringToC(JNIEnv *, jclass, jstring);

/**
 * Class: com_ooieuioo_potestjni_PoJNITtest
 * Method: TransportIntToC, Java send a integer to C, then C return (integer + 1) to Java
 * Signature: ()Ljava/lang/String
 */
JNIEXPORT jint JNICALL Java_com_ooieuioo_potestjni_PoJNITtest_TransportIntToC(JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
